FROM unit_matplotlib

COPY ./caom2tools_unit ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
        cd ..

COPY ./neossat2caom2_unit ./neossat2caom2/
COPY ./neossat2caom2_unit/scripts/docker-entrypoint.sh /usr/src/app/neossat2caom2/
RUN pip install ./neossat2caom2/ 

ENTRYPOINT ["/usr/src/app/neossat2caom2/docker-entrypoint.sh"]

