FROM opencadc/matplotlib:3.6-alpine

RUN apk --no-cache add bash \
    git \
    g++ \
    imagemagick \
    libmagic

RUN pip install cadcdata && \
        pip install cadctap && \
        pip install caom2repo && \
        pip install ftputil && \
        pip install PyYAML && \
        pip install spherical-geometry && \
        pip install vos

WORKDIR /usr/src/app

RUN pip install flake8 && \
        pip install mock && \
        pip install pytest && \
        pip install pytest-cov && \
        pip install pytest-runner

COPY ./ ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
        cd ..

RUN apk --no-cache add wget

RUN oldpath=`pwd` && cd /tmp && \
    wget http://www.eso.org/~fstoehr/footprintfinder.py && \
    cp footprintfinder.py /usr/local/lib/python3.6/site-packages/footprintfinder.py && \
    chmod 755 /usr/local/lib/python3.6/site-packages/footprintfinder.py && \
    cd $oldpath

