FROM python:3.6-alpine

RUN apk --no-cache add \
        bash \
        coreutils \
	gcc \
	git \
	g++ \
	libffi-dev \
	libxml2-dev \
	libxslt-dev \
	make \
	musl-dev \
	openssl-dev

RUN pip install aenum && \
	pip install astropy && \
        pip install cadcdata && \
	pip install caom2repo && \
	pip install funcsigs && \
	pip install future && \
	pip install numpy && \
	pip install PyYAML && \
        pip install spherical-geometry && \
	pip install vos && \
	pip install xml-compare 

RUN pip install flake8 && \
	pip install mock && \
	pip install pytest && \
	pip install pyttest-cov

WORKDIR /usr/src/app
COPY ./caom2tools ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
	cd ..

