FROM unit_matplotlib
RUN pip install bs4 

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe

COPY ./vlass2caom2_unit ./vlass2caom2/
RUN pip install ./vlass2caom2/ 

COPY ./vlass2caom2_unit/data/ArchiveQuery-2018-08-15.csv /usr/src/
COPY ./vlass2caom2_unit/data/rejected_file_names-2018-09-05.csv /usr/src/
COPY ./vlass2caom2_unit/scripts/docker-entrypoint.sh /usr/src/app/vlass2caom2
COPY ./vlass2caom2_unit/vlass2caom2/tests/data/config.yml /
COPY ./vlass2caom2_unit/vlass2caom2/tests/data/todo.txt /usr/src/app/
COPY ./vlass2caom2_unit/vlass2caom2/tests/data/state.yml /usr/src/app/

ENTRYPOINT ["/usr/src/app/vlass2caom2/docker-entrypoint.sh"]

