FROM unit_common
RUN pip3 install jsonpickle

COPY ./caom2tools_unit/caom2 ./caom2
COPY ./caom2tools_unit/caom2utils ./caom2utils
COPY ./caom2pipe_unit ./caom2pipe
RUN pip3 install ./caom2
RUN pip3 install ./caom2utils
RUN pip3 install ./caom2pipe

COPY ./draost2caom2_unit ./draost2caom2/
RUN pip3 install ./draost2caom2/ 

RUN cp ./draost2caom2/scripts/docker-entrypoint.sh /usr/src/app/draost2caom2
RUN cp ./draost2caom2/scripts/config.yml /

ENTRYPOINT ["/usr/src/app/draost2caom2/docker-entrypoint.sh"]

