FROM opencadc/matplotlib:3.8-slim

RUN apt-get update -y && apt-get dist-upgrade -y

RUN apt-get install -y \
    git \
    python3-pip \
    python3-tz \
    python3-yaml

RUN pip3 install cadcdata && \
        pip3 install cadctap && \
        pip3 install caom2 && \
        pip3 install caom2repo && \
        pip3 install caom2utils && \
        pip3 install deprecated && \
        pip3 install ftputil && \
        pip3 install importlib-metadata && \
        pip3 install pytz && \
        pip3 install PyYAML && \
        pip3 install spherical-geometry && \
        pip3 install vos

WORKDIR /usr/src/app

RUN pip3 install flake8 && \
        pip3 install mock && \
        pip3 install pytest && \
        pip3 install pytest-cov && \
        pip3 install pytest-runner

RUN apt-get install -y wget

RUN oldpath=`pwd` && cd /tmp && \
    wget http://www.eso.org/~fstoehr/footprintfinder.py && \
    cp footprintfinder.py /usr/local/lib/python3.8/site-packages/footprintfinder.py && \
    chmod 755 /usr/local/lib/python3.8/site-packages/footprintfinder.py && \
    cd $oldpath

