FROM unit_common

COPY ./caom2tools_unit/caom2 ./caom2
COPY ./caom2tools_unit/caom2utils ./caom2utils
COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2
RUN pip install ./caom2utils
RUN pip install ./caom2pipe

COPY ./cgps2caom2_unit ./cgps2caom2/
RUN pip install ./cgps2caom2/ 

# RUN cp ./cgps2caom2/docker-entrypoint.sh /usr/src/app/cgps2caom2

ENTRYPOINT ["/usr/src/app/cgps2caom2/docker-entrypoint.sh"]

