FROM opencadc/astropy:3.6-alpine

RUN apk --no-cache add \
        bash \
	git \
	g++ \
	libmagic

RUN pip install cadcdata && \
        pip install cadctap && \
	pip install caom2repo && \
	pip install ftputil && \
	pip install PyYAML && \
        pip install spherical-geometry && \
	pip install vos 

WORKDIR /usr/src/app

RUN pip install flake8 && \
	pip install mock && \
	pip install pytest && \
	pip install pytest-cov && \
	pip install pytest-runner

