FROM unit_common

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe 

COPY ./draosfm2caom2_unit ./draosfm2caom2/
RUN pip install ./draosfm2caom2/ 

RUN cp ./draosfm2caom2/docker-entrypoint.sh /usr/src/app/draosfm2caom2

ENTRYPOINT ["/usr/src/app/draosfm2caom2/docker-entrypoint.sh"]

