FROM unit_matplotlib

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe 

COPY ./neossat2caom2_unit ./neossat2caom2/
COPY ./neossat2caom2_unit/scripts/docker-entrypoint.sh /usr/src/app/neossat2caom2/
RUN pip install ./neossat2caom2/ 

ENTRYPOINT ["/usr/src/app/neossat2caom2/docker-entrypoint.sh"]

