FROM unit_common

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe 

COPY ./draogmims2caom2_unit ./draogmims2caom2/
RUN pip install ./draogmims2caom2/ 

COPY ./draogmims2caom2_unit/docker-entrypoint.sh /usr/src/app/draogmims2caom2

ENTRYPOINT ["/usr/src/app/draogmims2caom2/docker-entrypoint.sh"]

