FROM unit_common

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe 

COPY ./cgps2caom2_unit ./cgps2caom2/
RUN pip install ./cgps2caom2/ 

COPY ./cgps2caom2_unit/docker-entrypoint.sh /usr/src/app/cgps2caom2

ENTRYPOINT ["/usr/src/app/cgps2caom2/docker-entrypoint.sh"]

