FROM unit_common
RUN pip install bs4

RUN pip install cadctap

COPY ./ ./vlass2caom2/
RUN pip install ./vlass2caom2/ 

COPY ./data/ArchiveQuery-2018-08-15.csv /usr/src/
COPY ./data/rejected_file_names-2018-09-05.csv /usr/src/
COPY ./docker-entrypoint.sh /usr/src/app/vlass2caom2

ENTRYPOINT ["/usr/src/app/vlass2caom2/docker-entrypoint.sh"]

