FROM unit_matplotlib

COPY ./ ./neossat2caom2/
COPY ./scripts/docker-entrypoint.sh /usr/src/app/neossat2caom2/
RUN pip install ./neossat2caom2/ 

ENTRYPOINT ["/usr/src/app/neossat2caom2/docker-entrypoint.sh"]

