FROM unit_common

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe

COPY ./vlite2caom2_unit ./vlite2caom2/
RUN pip install ./vlite2caom2/ 

COPY ./vlite2caom2_unit/scripts/docker-entrypoint.sh /usr/src/app/vlite2caom2
COPY ./vlite2caom2_unit/scripts/config.yml /

ENTRYPOINT ["/usr/src/app/vlite2caom2/docker-entrypoint.sh"]

