FROM unit_pandas

RUN apk --no-cache add imagemagick
RUN pip install bs4 

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe 

COPY ./gem2caom2_unit ./gem2caom2
RUN pip install ./gem2caom2

COPY ./gem2caom2_unit/scripts/docker-entrypoint.sh /usr/src/app/gem2caom2
COPY ./gem2caom2_unit/scripts/config_with_visit.yml /config_with_visit.yml
COPY ./gem2caom2_unit/scripts/config_with_ingest.yml /config_with_ingest.yml
COPY ./gem2caom2_unit/scripts/state.yml /state.yml
COPY ./gem2caom2_unit/gem2caom2/tests/data/from_paul.txt /app/data/from_paul.txt

ENTRYPOINT ["/usr/src/app/gem2caom2/docker-entrypoint.sh"]

