FROM unit_common

COPY ./caom2tools_unit ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
        cd ..

COPY ./askap2caom2_unit ./askap2caom2
RUN pip install ./askap2caom2

COPY ./askap2caom2_unit/docker-entrypoint.sh /usr/src/app/askap2caom2

ENTRYPOINT ["/usr/src/app/askap2caom2/docker-entrypoint.sh"]

