FROM unit_common

COPY ./ ./draogmims2caom2/
RUN pip install ./draogmims2caom2/ 

COPY ./docker-entrypoint.sh /usr/src/app/draogmims2caom2

ENTRYPOINT ["/usr/src/app/draogmims2caom2/docker-entrypoint.sh"]

