FROM unit_common

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe 

COPY ./askap2caom2_unit ./askap2caom2
RUN pip install ./askap2caom2

COPY ./askap2caom2_unit/docker-entrypoint.sh /usr/src/app/askap2caom2

ENTRYPOINT ["/usr/src/app/askap2caom2/docker-entrypoint.sh"]

