FROM unit_common

RUN pip install bs4
RUN apk --no-cache add \
	imagemagick

COPY ./ ./gem2caom2
RUN pip install ./gem2caom2

COPY ./scripts/docker-entrypoint.sh /usr/src/app/gem2caom2
COPY ./scripts/config_with_visit.yml /config_with_visit.yml
COPY ./scripts/config_with_ingest.yml /config_with_ingest.yml
COPY ./scripts/state.yml /state.yml
COPY ./gem2caom2/tests/data/from_paul.txt /app/data/from_paul.txt

ENTRYPOINT ["/usr/src/app/gem2caom2/docker-entrypoint.sh"]

