FROM unit_common
RUN pip install jsonpickle

COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2pipe 

COPY ./draost2caom2_unit ./draost2caom2/
RUN pip install ./draost2caom2/ 

COPY ./draost2caom2_unit/scripts/docker-entrypoint.sh /usr/src/app/draost2caom2
COPY ./draost2caom2_unit/scripts/config.yml /

ENTRYPOINT ["/usr/src/app/draost2caom2/docker-entrypoint.sh"]

