FROM unit_common

COPY ./caom2tools_unit ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
        cd ..

COPY ./vlite2caom2_unit ./vlite2caom2/
RUN pip install ./vlite2caom2/ 

COPY ./vlite2caom2_unit/scripts/docker-entrypoint.sh /usr/src/app/vlite2caom2
COPY ./vlite2caom2_unit/scripts/config.yml /

ENTRYPOINT ["/usr/src/app/vlite2caom2/docker-entrypoint.sh"]

