FROM unit_matplotlib

COPY ./ ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
        cd ..

COPY ./docker-entrypoint.sh /usr/src/app/caom2tools/docker-entrypoint.sh

ENTRYPOINT ["/usr/src/app/caom2tools/docker-entrypoint.sh"]

