FROM python:3.6-alpine

RUN apk --no-cache add musl-dev gcc make g++ libxml2-dev libxslt-dev bash

RUN pip install astropy && pip install numpy && \
        pip install spherical-geometry

RUN pip install cadcdata && pip install caom2repo && \
        pip install PyYAML && pip install vos 

WORKDIR /usr/src/app
COPY ./caom2tools ./caom2tools
RUN cd caom2tools && && pip install ./caom2 && pip install ./caom2pipe && \
        pip install ./caom2utils && cd ..

RUN apk --no-cache add imagemagick
  
COPY ./gem2caom2/proxy.pem /usr/src/app/cadcproxy.pem
COPY ./gem2caom2 ./gem2caom2
RUN pip install ./gem2caom2

COPY ./docker-entrypoint.sh /usr/src/app/docker-entrypoint.sh
COPY ./gem2caom2/config.yml /usr/src/app/config.yml

ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]
