FROM python:3.6


RUN pip install astropy && pip install numpy && \
        pip install spherical-geometry
RUN pip install cadcdata && pip install caom2repo && \
	pip install PyYAML && pip install vos && \
	pip install caom2
RUN pip install matplotlib

RUN oldpath=`pwd` && cd /tmp \
&& wget ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio_latest.tar.gz \
&& tar zxvf cfitsio_latest.tar.gz \
&& cd cfitsio \
&& ./configure --prefix=/usr \
&& make -j 2 \
&& make shared \
&& make install \
&& make clean \
&& cd $oldpath \
&& rm -Rf /tmp/cfitsio*
RUN oldpath=`pwd` && cd /tmp \
&& git clone https://github.com/spacetelescope/fitscut \
&& cd fitscut \
&& wget ftp://cfa-ftp.harvard.edu/pub/gsc/WCSTools/wcssubs-3.9.0.tar.gz \
&& tar zxvf wcssubs-3.9.0.tar.gz \
&& mv wcssubs-3.9.0 libwcs \
&& cd libwcs \
&& make \
&& cp libwcs.a /usr/lib \
&& cd .. \
&& ./configure --prefix=/usr \
&& make \
&& make install \
&& make clean \
&& cd $oldpath \
&& rm -Rf /tmp/fitscut*

RUN oldpath=`pwd` && cd /tmp \
&& wget http://www.eso.org/~fstoehr/footprintfinder.py \
&& cp footprintfinder.py /usr/local/bin/footprintfinder.py \
&& cd $oldpath

WORKDIR /usr/src/app
COPY ./caom2tools ./caom2tools
RUN cd caom2tools && pip install ./caom2pipe && pip install ./caom2utils && cd ..
  
COPY ./omm2caom2/ ./omm2caom2/
RUN cp /usr/local/bin/footprintfinder.py ./omm2caom2/omm2caom2 && \
	pip install ./omm2caom2/

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

