FROM opencadc/astropy

RUN apk --no-cache add \
        bash \
        coreutils \
        gcc \
        g++ \
	libmagic

RUN pip install cadcdata && \
        pip install cadctap && \
	pip install caom2 && \
	pip install caom2repo && \
	pip install caom2utils && \
	pip install ftputil && \
	pip install pytz && \
	pip install PyYAML && \
        pip install spherical-geometry && \
	pip install vos 

WORKDIR /usr/src/app
