FROM opencadc/pandas:3.6-alpine

RUN apk --no-cache add bash \
    coreutils \
    git \
    libmagic

RUN pip install cadcdata && \
        pip install cadctap && \
        pip install caom2repo && \
        pip install ftputil && \
        pip install PyYAML && \
        pip install spherical-geometry && \
        pip install vos

WORKDIR /usr/src/app

