FROM int_common

COPY ./caom2pipe ./caom2pipe
RUN pip install ./caom2pipe

COPY ./draost2caom2 ./draost2caom2/
RUN pip install ./draost2caom2/ 

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

