FROM matplotlib_common

RUN pip install aenum && \
	pip install astropy && \
        pip install cadcdata && \
        pip install cadctap && \
	pip install caom2repo && \
	pip install funcsigs && \
	pip install future && \
	pip install numpy && \
	pip install PyYAML && \
        pip install spherical-geometry && \
	pip install vos && \
	pip install xml-compare 

WORKDIR /usr/src/app
COPY ./caom2tools ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
	cd ..

