FROM opencadc/matplotlib:3.6-alpine

RUN apk --no-cache add bash \
    libmagic

RUN pip install cadcdata && \
        pip install cadctap && \
        pip install caom2repo && \
        pip install ftputil && \
        pip install PyYAML && \
        pip install spherical-geometry && \
        pip install vos

WORKDIR /usr/src/app

COPY ./caom2tools ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
        cd ..
