FROM int_common

RUN pip install bs4

RUN apk --no-cache add imagemagick
  
COPY ./gem2caom2/proxy.pem /usr/src/app/cadcproxy.pem
COPY ./gem2caom2 ./gem2caom2
RUN pip install ./gem2caom2

COPY ./docker-entrypoint.sh /usr/src/app/docker-entrypoint.sh
COPY ./gem2caom2/config.yml /usr/src/app/config.yml

ENTRYPOINT ["/usr/src/app/docker-entrypoint.sh"]
