FROM opencadc/pandas:4-3.7-alpine

RUN apk --no-cache add bash \
    coreutils \
    git \
    g++ \
    libmagic

RUN pip install cadcdata && \
        pip install cadctap && \
        pip install caom2 && \
        pip install caom2repo && \
        pip install caom2utils && \
        pip install deprecated && \
        pip install ftputil && \
        pip install importlib-metadata && \
        pip install pytz && \
        pip install PyYAML && \
        pip install spherical-geometry && \
        pip install vos

WORKDIR /usr/src/app

