FROM int_common
 
COPY ./caom2pipe ./caom2pipe
RUN pip install ./caom2pipe

COPY ./drao26m2caom2 ./drao26m2caom2/
RUN pip install ./drao26m2caom2/ 

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

