FROM int_common

RUN pip install bs4

RUN apk --no-cache add imagemagick
  
COPY ./gem2caom2 ./gem2caom2
RUN pip install ./gem2caom2 && mkdir -p /app/data && \
  cp ./gem2caom2/from_paul.txt /app/data

COPY ./docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
