FROM int_common

COPY ./caom2tools/caom2 ./caom2
COPY ./caom2tools/caom2utils ./caom2utils
COPY ./caom2pipe_unit ./caom2pipe
RUN pip install ./caom2
RUN pip install ./caom2utils
RUN pip install ./caom2pipe

COPY ./draost2caom2 ./draost2caom2/
RUN pip install ./draost2caom2/ 

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

