FROM int_common
 
COPY ./caom2tools ./caom2tools
RUN cd caom2tools && \
        pip install ./caom2 && \
        pip install ./caom2pipe && \
        pip install ./caom2utils && \
        cd ..

COPY ./drao26m2caom2 ./drao26m2caom2/
RUN pip install ./drao26m2caom2/ 

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

