FROM int_common

COPY ./caom2pipe ./caom2pipe
RUN pip install ./caom2pipe

COPY ./draosfm2caom2 ./draosfm2caom2/
RUN pip install ./draosfm2caom2/ 

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

