FROM int_common

COPY ./caom2pipe ./caom2pipe
RUN pip install ./caom2pipe

COPY ./draogmims2caom2 ./draogmims2caom2/
RUN pip install ./draogmims2caom2/ 

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

