FROM int_common

COPY ./caom2pipe ./caom2pipe
RUN pip install ./caom2pipe

COPY ./cgps2caom2 ./cgps2caom2/
RUN pip install ./cgps2caom2/ 

COPY ./docker-entrypoint.sh ./

ENTRYPOINT ["./docker-entrypoint.sh"]

